services:
  grocery-app:
    image: grocery-app:v1
    build: .
    ports:
      - 8080:8080
    depends_on:
      - grocery-mysql
      - cache
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - CACHE_HOST=${CACHE_HOST}
      - CACHE_PORT=${CACHE_PORT}
    
  grocery-mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - 3306:3306
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
  
  cache:
    image: redis:7-alpine
    ports:
      - 6379:6379
    command: redis-server --save 60 1 --loglevel warning

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
 # TODO - Modify this
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=${GF_AUTH_ANONYMOUS_ENABLED}
      - GF_AUTH_ANONYMOUS_ORG_ROLE=${GF_AUTH_ANONYMOUS_ORG_ROLE}


  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
# TODO - Modify this
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
